### ISSUE TITLE
zadanie 3

### ISSUE THREAD

**Issue by MikolajSzczepkowski** [CodeCarrotsJS/laboratorium#1]
Mam problem, nie wiem jak sprawić, żeby dodawała się odpowiednia ilość 'li'
http://jsbin.com/xokanoxexa/1/edit?html,js,output

**Comment by Lksz** [comment]
Właśnie przed chwilą googlowałem dla siebie :-)
[i google mówi](http://stackoverflow.com/questions/12730824/appendchild-in-for-loop-only-adds-1-child): 

> You are appending the same element over and over.
> You need to call document.createElement each time you wish to have a new element.

a więc `var li = document.createElement('li');`
powinno być wewnątrz pętli, żeby przy każdym jej przebiegu
utworzyć nowy element `li`.
[Przykład JSbin](http://jsbin.com/nekucakoso/1/edit?html,css,js,output)

**Comment by adelura** [comment]
Prawie wszystko masz dobrze, jednak pewną część kodu wykonujesz raz, a powinieneś wrzucić do pętli.

**Comment by adelura** [comment]
O, w trakcie pisania odpisał Łukasz :) Good job!

**Comment by MikolajSzczepkowski** [comment]
Tak, teraz to wydaje się oczywiste :) Dzięki
