### ISSUE TITLE
manipulowanie stylami w praktyce

### ISSUE THREAD

**Issue by Lksz** [CodeCarrotsJS/laboratorium#2]
Mam pytanie, w stylue "jak to wygląda naprawdę".

Czy istnieje szerzej przyjęty wzorzec, jeśli chodzi o stylowanie elementów stron przez JS?
##### Podejście pierwsze:

Dla tego, co możliwe styluje się odpowiednie klasy/id w CSS, a później
JSem tylko odpowiednim elementom te nadaje/usuwa się klasy.
##### Podejście drugie:

Tam, gdzie to możliwe elementy styluje się bezpośrednio w JS/jQuery/inne?

Wydaje mi, że łatwiej jest zapanować na projektem w podejściu pierwszym.

Ale może nie ma konkretnych zaleceń i wszystko zależy od indywidualnych preferencji?

Przykład: mobilne menu.
W podejściu pierwszym w css menu ma odpowiednie: `display, height, transition` itp.,
w JS dodaję Listenera, który będzie tylko usuwał/nadawał klasę "visible".

W podejściu drugim cała animacja robiona jest w JS.

**Comment by gpks** [comment]
Zdecydowanie pierwsze podejście jest 'poprawniejsze', więc miałeś dobrą intuicję. 
to kwestia porządku w projekcie, cssy to cssy, trzymamy je w arkuszach styli, a w JS tylko manipulujemy nimi.

**Comment by Lksz** [comment]
Dzięki!
