### ISSUE TITLE
Problem z zadaniem Termometr

### ISSUE THREAD

**Issue by flamenco88** [CodeCarrotsJS/laboratorium#4]
Hej,

Utknęłam z zadaniem - Termometr (https://gist.github.com/adelura/bbf7dee93bf14a2229b9), wydaje mi się, że wszystko jest w porządku, ale niestety nie chce zadziałać i pojawia się jakiś błąd w form.addEventListener('submit', function(e) zauważyłam, że ma jakiś problem z form. Po zmianie forma na document, błąd się nie pojawia, ale mimo to funkcja nie chce działać. Jeśli mogłabym prosić o jakąś podpowiedź.
Projekt na GitHub: https://github.com/flamenco88/Termometr.git

Pozdrawiam,

Ania :)

**Comment by adelura** [comment]
W [pierwszej linijce](https://github.com/flamenco88/Termometr/blob/master/js/termometr.js#L1) wywołujesz funkcję `getElementsByTagName`. Funkcja ta zwraca tablicę elementów, nawet jeżeli na stronie jest jeden element, więc próbujesz wywołać funkcję `addEventListener` na tablicy.
