### ISSUE TITLE
usuwanie niestniejącej klasy

### ISSUE THREAD

**Issue by Lksz** [CodeCarrotsJS/laboratorium#5]
Czy akceptowalne jest wykonywanie `classList.remove(nazwaKlasy)` na elemencie strony, który może w momencie wywołania tej klasy może nie posiadać?
Czy raczej tzw. dobre praktyki nakazują sprawdzenie czy element posiada klasę i dopiero wtedy ew. ją usunąć?
Pierwsze rozwiązanie to mniej kodu do napisania, ale wygląda trochę nieelegancko. Z drugiej strony spora ilość dodatkowego kodu do tak nieskomplikowanej rzeczy też nie wygląda dobrze.

**Comment by adelura** [comment]
funckja remove sprawdza, czy element posiada daną klasę, więc nie ma potrzeby sprawdzania drugi raz.

**Comment by Lksz** [comment]
Dzięki!
