### ISSUE TITLE
Zadanie "Rok przestępny" - część z liczeniem dnia roku

### ISSUE THREAD

**Issue by katkor** [CodeCarrotsJS/laboratorium#7]
Mam problem z kodem obliczającym, który jest dzień roku (https://gist.github.com/adelura/f8bc26c78ec67b8e2960 - część "Trudne sprawy").
Napisałam coś takiego: http://jsbin.com/rubuzi/3/edit?html,js,output ale gdzieś się pomyliłam, bo dla stycznia liczy w porządku, ale dla dalszych miesięcy nie: dla przykładu, 31 stycznia to 31. dzień roku (czyli ok), ale już 1 lutego to... 131 dzień roku, 2 lutego - 231 dzień roku itd., czyli program dodaje 100 dla każdego kolejnego dnia po styczniu. Czy ktoś może mi wskazać, gdzie zrobiłam błąd i jaki? ;)

**Comment by gpks** [comment]
Kasiu, sprawdź jaki typ danych przychodzi z formularza...

**Comment by katkor** [comment]
Zmyliło mnie to, że chyba na zajęciach mówiliście, że z formularza typu "number" pobierane są dane typu liczbowego, więc nawet o tym nie pomyślałam... Ale może coś źle zrozumiałam. Dzięki :)

**Comment by gpks** [comment]
Musieliśmy się pomylić :( przynajmniej wg tego artykulu http://www.w3schools.com/jsref/prop_number_value.asp
