### ISSUE TITLE
Prośba o pomoc z ajaxowym zadaniem

### ISSUE THREAD

**Issue by bezliku** [CodeCarrotsJS/laboratorium#9]
Hej!

Zrobiłam większość zadania z ajaxem, tutaj mój kod z komentarzami:
https://github.com/bezliku/CC_GitHub_AJAX

Mam jednak problem z jedną rzeczą:
Jest tak: Mam posty, które mają ukryte akapity z treścią i zawierają buttony "Przeczytaj". 
Zamierzenie: po kliknięciu w "Przeczytaj", odsłania się treść postu.
Co robię: Podczas dodawania postu, nadaję tym buttonom klasę "readMore". Następnie modyfikuję elementy z tą klasą, tak aby po kliknięciu pojawiał się paragraf. I wszystko śmiga dla postów, które są już zapisane. Przy dodawaniu nowych - nie działa.

Jeśli komuś chciałoby się w to zerknąć i coś mi podpowiedzieć to byłabym wdzięczna :)
Przy okazji chętnie bym się dowiedziała jakie błędy w kodzie popełniłam.

Pozdrawiam!
Marta

**Comment by adelura** [comment]
Problem polega na tym, że w [tym momencie](https://github.com/bezliku/CC_GitHub_AJAX/blob/master/public/custom.js#L42) dodajesz nasłuchiwanie na elementach, które są dostępne właśnie w tym momencie na stronie. Nowy post dodałaś później, więc dla nowo dodanego elementu ta funckja się nie wykona.

Rozwiązaniem może być nasłuchiwanie kliknięcia elementu `<div class="readMore"></div>`, który tworzysz w funkcji [createPost](https://github.com/bezliku/CC_GitHub_AJAX/blob/master/public/custom.js#L3), wtedy to zadziała dla każdego nowo dodanego elementu.

Dodatkowo w ramach nowego wyzwania i ćwiczeń polecam zapoznanie sie z artykułem: [An Introduction To Dom Events](http://www.smashingmagazine.com/2013/11/12/an-introduction-to-dom-events/) - sekcja "Delegate Event Listeners".

**Comment by bezliku** [comment]
Działa, dziękuję! :)
